Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-01da99628f381e50a
      KeyName: SingaPore
      Tags:
        - Key: Name
          Value: DB-Server
        - Key: Type
          Value: MYSQL
      SecurityGroups:
        - !Ref MySecurityGroup


  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: SecurityGroup1
      GroupDescription: This is SecurityGroup1
      SecurityGroupIngress:
        - CidrIp: 165.225.106.81/32
          Description: SSH
          FromPort: 22
          IpProtocol: TCP
          ToPort: 22
        - CidrIp: 165.225.106.81/32
          Description: ICMP
          FromPort: -1
          IpProtocol: ICMP
          ToPort: -1
      Tags:
        - Key: Name
          Value: SecurityGroup_Singapore